package com.callify.data.local

import androidx.room.Dao
import androidx.room.Insert
import androidx.room.OnConflictStrategy
import androidx.room.Query
import com.callify.data.model.CallLogEntry

/**
 * DAO for the call_log table.
 *
 * All queries here are for internal database integrity only.
 * No query result is ever surfaced in the application UI.
 * Filtering and export are performed externally via ADB shell.
 */
@Dao
interface CallLogDao {

    /**
     * Inserts a new call log entry.
     * Called once per incoming call after lookup resolves.
     * ABORT strategy — primary key is autoGenerated so duplicates
     * are impossible in normal operation; this is a safety net only.
     */
    @Insert(onConflict = OnConflictStrategy.ABORT)
    suspend fun insert(entry: CallLogEntry)

    /**
     * Returns total record count.
     * Used by ADB verification only — not called from any UI.
     */
    @Query("SELECT COUNT(*) FROM call_log")
    suspend fun count(): Int
}
