package com.callify.di

import com.callify.BuildConfig
import com.callify.data.model.CallerInfo
import com.callify.data.remote.CallerApiClient
import dagger.Module
import dagger.Provides
import dagger.hilt.InstallIn
import dagger.hilt.components.SingletonComponent
import okhttp3.ConnectionPool
import okhttp3.OkHttpClient
import okhttp3.logging.HttpLoggingInterceptor
import retrofit2.Retrofit
import retrofit2.converter.gson.GsonConverterFactory
import java.util.Collections
import java.util.concurrent.TimeUnit
import javax.inject.Singleton

/**
 * Hilt module for providing network-related dependencies.
 *
 * Provides:
 *  - [OkHttpClient]     — timeouts, logging, (optional) auth
 *  - [Retrofit]         — pointed at [BuildConfig.CALLIFY_API_BASE_URL]
 *  - [CallerApiClient]  — Retrofit implementation of the lookup interface
 *  - [MutableMap]       — in-memory LRU cache for [CallerInfo] (max 50 entries)
 */
@Module
@InstallIn(SingletonComponent::class)
object NetworkModule {

    /**
     * Provides a configured [OkHttpClient].
     *
     * Timeouts:
     *   - connect : 3 s
     *   - read    : 4 s
     *   - write   : 3 s
     *
     * Auth interceptor is present but commented out.
     * Uncomment and supply the key when the API requires authentication.
     */
    @Provides
    @Singleton
    fun provideOkHttpClient(): OkHttpClient {
        val loggingInterceptor = HttpLoggingInterceptor().apply {
            level = if (BuildConfig.DEBUG) HttpLoggingInterceptor.Level.BODY
                    else HttpLoggingInterceptor.Level.NONE
        }

        return OkHttpClient.Builder()
            .connectTimeout(3, TimeUnit.SECONDS)
            .readTimeout(4, TimeUnit.SECONDS)
            .writeTimeout(3, TimeUnit.SECONDS)
            .connectionPool(ConnectionPool(5, 30, TimeUnit.SECONDS))
            .retryOnConnectionFailure(false)

            .addInterceptor(loggingInterceptor)
            .build()
    }

    /**
     * Retrofit instance pointed at [BuildConfig.CALLIFY_API_BASE_URL].
     *
     * Active endpoints:
     *   POST /lookup  →  [CallerApiClient.lookup]
     *
     * To add a future endpoint:
     *   1. Add the suspend fun to [CallerApiClient]
     *   2. Add the request/response data class to data.model
     *   3. Add the call site to [CallerRepository]
     *   4. Annotate with the CALLIFY API CALL block format
     */
    @Provides
    @Singleton
    fun provideRetrofit(okHttpClient: OkHttpClient): Retrofit {
        return Retrofit.Builder()
            .baseUrl(BuildConfig.CALLIFY_API_BASE_URL)
            .client(okHttpClient)
            .addConverterFactory(GsonConverterFactory.create())
            .build()
    }

    /**
     * Provides the [CallerApiClient] interface implementation generated by Retrofit.
     */
    @Provides
    @Singleton
    fun provideCallerApiClient(retrofit: Retrofit): CallerApiClient {
        return retrofit.create(CallerApiClient::class.java)
    }

    /**
     * In-memory LRU cache for [CallerInfo] objects.
     * Max 50 entries, evicted by least-recently-used policy.
     * Prevents duplicate API calls for the same number within a session.
     */
    @Provides
    @Singleton
    fun provideCallerCache(): MutableMap<String, CallerInfo> {
        return Collections.synchronizedMap(
            object : LinkedHashMap<String, CallerInfo>(50, 0.75f, true) {
                override fun removeEldestEntry(eldest: MutableMap.MutableEntry<String, CallerInfo>): Boolean {
                    return size > 50
                }
            }
        )
    }
}
